function res = ProblemConditions(nb_harmonics, deformation_amplitudes, deformation_velocities, ...
       pressure_deformation, current_time, dt, center_of_mass, center_of_mass_velocity, nb_contact_points)

res = struct( ...
            "nb_harmonics", nb_harmonics, "deformation_amplitudes", deformation_amplitudes, ...
            "deformation_velocities", deformation_velocities, "pressure_deformation", pressure_deformation, ...
            "current_time", current_time, "dt", dt, "center_of_mass", center_of_mass, "center_of_mass_velocity", ...
            center_of_mass_velocity, "nb_contact_points", nb_contact_points);
        
end