function coefs = project_amplitudes(ff, harmonics_qtt, endpoints, PROBLEM_CONSTANTS) 
    coefs = arrayfun(@(idx) ...
        (2*idx+1)/2 * integral(@(theta) PROBLEM_CONSTANTS.LEGENDRE_POLYNOMIALS{idx}(cos(theta)) ...
        .* ff(theta) .* sin(theta), endpoints(1), endpoints(2), ...
        'AbsTol', 1e-3, 'RelTol', 5e-2), 1:harmonics_qtt);
end